# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  api_testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: dannydainton/htmlextra
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Newman Run
        run: newman run .github/workflows/Books-API.postman_collection.json --reporters cli,htmlextra
      - name: Commit report
        uses: EndBug/add-and-commit@v9
        with: 
          default_author: github_actions
        
        #run: |
          
          #git config --global user.name 'kristinastoyanovax'
          #git config --global user.email 'christina.st.stoyanova@gmail.com'
          #git commit -am "Automated report"
          #git push
